from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
import time
from datetime import datetime
from pathlib import Path

from gow_monitor.infrastructure import (
    GowFilesystemRunReader,
    GowProcessTreeReader,
    SystemResourceReader,
)


def build_parser() -> argparse.ArgumentParser:
    monitor_root = Path(__file__).resolve().parents[1]
    default_gow_root = monitor_root.parent / "generic-optimization-workflow"

    parser = argparse.ArgumentParser(
        description=(
            "Run a real GOW Differential Evolution campaign and validate "
            "live Host RAM, GOW RSS, artifact growth and final evaluation count."
        )
    )
    parser.add_argument(
        "--gow-root",
        type=Path,
        default=default_gow_root,
        help="Root directory of the generic-optimization-workflow repository.",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=None,
        help=(
            "Optional GOW output directory. When omitted, every validation "
            "gets a brand-new isolated temporary directory."
        ),
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Run identifier. A timestamped ID is generated by default.",
    )
    parser.add_argument(
        "--evaluations",
        type=int,
        default=10_000,
        help="Real GOW evaluations to execute.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="GOW optimizer batch size.",
    )
    parser.add_argument(
        "--sample-interval-ms",
        type=int,
        default=500,
        help="Console resource sampling interval.",
    )
    parser.add_argument(
        "--no-launch-monitor",
        action="store_true",
        help="Run the validation without opening GOW Monitor.",
    )
    return parser


def gow_executable(gow_root: Path) -> Path:
    if sys.platform.startswith("win"):
        return gow_root / ".venv" / "Scripts" / "gow.exe"
    return gow_root / ".venv" / "bin" / "gow"


def write_spec(
    *,
    path: Path,
    evaluator: Path,
    evaluations: int,
    batch_size: int,
) -> None:
    max_generations = max(100, evaluations // max(1, batch_size) + 10)
    evaluator_yaml = str(evaluator).replace("\\", "/")

    text = f"""id: monitor-real-resource-validation

objective:
  direction: minimize

parameters:
  x:
    type: real
    value: 0.1
    bounds: [-5.0, 5.0]

  y:
    type: real
    value: -0.2
    bounds: [-5.0, 5.0]

  n:
    type: int
    value: 5
    optimizable: false

  mode:
    type: categorical
    value: a
    optimizable: false

evaluator:
  command: ["{{python}}", "{evaluator_yaml}"]
  timeout_s: 60
  env:
    OMP_NUM_THREADS: "1"

optimizer:
  name: differential_evolution
  seed: 123
  max_evaluations: {evaluations}
  batch_size: {batch_size}

  settings:
    mutation_factor: 0.8
    crossover_rate: 0.9
    max_generations: {max_generations}

context:
  note: "Real GOW resource telemetry validation"
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    args = build_parser().parse_args()

    if args.evaluations < 1:
        raise ValueError("--evaluations must be positive")
    if args.batch_size < 1:
        raise ValueError("--batch-size must be positive")
    if args.sample_interval_ms < 100:
        raise ValueError("--sample-interval-ms must be at least 100")

    gow_root = args.gow_root.expanduser().resolve()
    run_id = args.run_id or (
        "real-gow-resource-"
        + datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    )

    if args.outdir is None:
        outdir = (
            Path(tempfile.gettempdir())
            / "gow_real_resource_validation"
            / run_id
        ).resolve()
    else:
        outdir = args.outdir.expanduser().resolve()

    executable = gow_executable(gow_root)
    evaluator = gow_root / "tests" / "toy_eval.py"

    if not executable.is_file():
        raise FileNotFoundError(
            f"GOW executable not found: {executable}"
        )
    if not evaluator.is_file():
        raise FileNotFoundError(
            f"Official toy evaluator not found: {evaluator}"
        )

    run_root = outdir / "runs" / run_id
    if run_root.exists():
        raise FileExistsError(
            "Refusing to reuse an existing validation run: "
            f"{run_root}"
        )

    outdir.mkdir(parents=True, exist_ok=True)
    validation_root = outdir / "_validation_specs"
    validation_root.mkdir(parents=True, exist_ok=True)
    spec_path = validation_root / f"{run_id}.yaml"

    write_spec(
        path=spec_path,
        evaluator=evaluator,
        evaluations=args.evaluations,
        batch_size=args.batch_size,
    )

    command = [
        str(executable),
        "run",
        str(spec_path),
        "--outdir",
        str(outdir),
        "--run-id",
        run_id,
    ]

    print("=== REAL GOW RESOURCE VALIDATION ===")
    print(f"GOW root: {gow_root}")
    print(f"GOW executable: {executable}")
    print(f"Evaluator: {evaluator}")
    print(f"Output directory: {outdir}")
    print(f"Run ID: {run_id}")
    print(f"Expected run root: {run_root}")
    print(f"Evaluations: {args.evaluations:,}")
    print(f"Batch size: {args.batch_size:,}")
    print("")
    print("Starting REAL gow.exe ...")

    gow_process = subprocess.Popen(
        command,
        cwd=gow_root,
        text=True,
    )

    print(f"REAL GOW PID: {gow_process.pid}")

    monitor_process: subprocess.Popen[str] | None = None
    if not args.no_launch_monitor:
        deadline = time.monotonic() + 15.0
        while (
            gow_process.poll() is None
            and not run_root.is_dir()
            and time.monotonic() < deadline
        ):
            time.sleep(0.05)

        if not run_root.is_dir():
            gow_process.terminate()
            gow_process.wait(timeout=10)
            raise RuntimeError(
                "GOW did not create the new run directory in time: "
                f"{run_root}"
            )

        monitor_process = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "gow_monitor",
                "--results-root",
                str(run_root),
                "--gow-pid",
                str(gow_process.pid),
            ],
            cwd=Path.cwd(),
            text=True,
        )
        print(f"GOW Monitor PID: {monitor_process.pid}")
        print(f"Monitor connected directly to: {run_root}")

    host_reader = SystemResourceReader(gpu_readers=())
    gow_reader = GowProcessTreeReader(gow_process.pid)

    sample_interval = args.sample_interval_ms / 1000.0

    host_samples = 0
    gow_samples = 0
    gow_rss_values: list[int] = []
    artifact_counts: list[int] = []

    while gow_process.poll() is None:
        host = host_reader.snapshot()
        gow = gow_reader.snapshot()

        generation_root = run_root / "generations"
        artifact_count = (
            len(tuple(generation_root.glob("g*.jsonl")))
            if generation_root.is_dir()
            else 0
        )
        artifact_counts.append(artifact_count)

        host_samples += 1

        if gow.available and gow.memory_rss_bytes is not None:
            gow_samples += 1
            gow_rss_values.append(gow.memory_rss_bytes)
            gow_rss_text = (
                f"{gow.memory_rss_bytes / 1024**2:.2f} MiB"
            )
            process_text = (
                f"{gow.process_count} proc / "
                f"{gow.thread_count} threads"
            )
        else:
            gow_rss_text = "N/A"
            process_text = gow.status

        print(
            "[live] "
            f"host_ram={host.memory_percent:.2f}% | "
            f"gow_rss={gow_rss_text} | "
            f"{process_text} | "
            f"artifact_sources={artifact_count}",
            flush=True,
        )

        time.sleep(sample_interval)

    return_code = gow_process.wait()
    print("")
    print(f"GOW return code: {return_code}")

    time.sleep(0.75)

    reader = GowFilesystemRunReader(run_root)
    references = tuple(reader.discover_runs())

    failures: list[str] = []

    if return_code != 0:
        failures.append(
            f"real GOW process returned exit code {return_code}"
        )

    if gow_samples < 3:
        failures.append(
            f"only {gow_samples} live GOW RSS samples were available"
        )

    if not gow_rss_values or max(gow_rss_values) <= 0:
        failures.append(
            "GOW RSS never reported a positive resident-memory value"
        )

    if not references:
        final_snapshot = None
        failures.append("the real GOW run was not discovered")
    else:
        final_snapshot = reader.snapshot_of(references[0])
        if final_snapshot.evaluation_count != args.evaluations:
            failures.append(
                "final evaluation count mismatch: "
                f"{final_snapshot.evaluation_count:,} != "
                f"{args.evaluations:,}"
            )

    print("")
    print("=== REAL GOW RESOURCE SUMMARY ===")
    print(f"Host samples: {host_samples}")
    print(f"Live GOW RSS samples: {gow_samples}")
    print(
        "GOW RSS range: "
        f"{min(gow_rss_values, default=0) / 1024**2:.2f} - "
        f"{max(gow_rss_values, default=0) / 1024**2:.2f} MiB"
    )
    print(
        "Maximum artifact sources observed live: "
        f"{max(artifact_counts, default=0)}"
    )
    print(
        "Final evaluations: "
        f"{final_snapshot.evaluation_count if final_snapshot else 0:,} / "
        f"{args.evaluations:,}"
    )

    if failures:
        print("")
        print("REAL GOW RESOURCE VALIDATION FAILED")
        for failure in failures:
            print(f" - {failure}")
        return 2

    print("")
    print("REAL GOW RESOURCE VALIDATION PASSED")
    print(
        "A real gow.exe process was executed and its live RSS was measured."
    )
    print(
        "The monitor remains open so the final UI state can be inspected."
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
