from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
import time
from datetime import datetime
from pathlib import Path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Launch the official GOW toy campaign and attach GOW Monitor "
            "to its real operating-system process tree."
        )
    )
    parser.add_argument(
        "--gow-root",
        type=Path,
        required=True,
        help="Root of the generic-optimization-workflow repository.",
    )
    parser.add_argument(
        "--outdir",
        type=Path,
        default=Path(tempfile.gettempdir()) / "gow_real_resource_smoke",
        help="Output directory observed by GOW Monitor.",
    )
    parser.add_argument(
        "--run-id",
        default=None,
        help="Run identifier. A timestamped value is generated by default.",
    )
    parser.add_argument(
        "--no-launch-monitor",
        action="store_true",
        help="Execute GOW without starting a second monitor process.",
    )
    return parser


def gow_executable(gow_root: Path) -> Path:
    if os.name == "nt":
        return gow_root / ".venv" / "Scripts" / "gow.exe"
    return gow_root / ".venv" / "bin" / "gow"


def main() -> int:
    arguments = build_parser().parse_args()
    gow_root = arguments.gow_root.expanduser().resolve()
    outdir = arguments.outdir.expanduser().resolve()
    run_id = arguments.run_id or (
        "resource-live-smoke-" + datetime.now().strftime("%Y%m%d-%H%M%S")
    )

    executable = gow_executable(gow_root)
    specification = gow_root / "examples" / "toy" / "optimization_specs.yaml"

    if not executable.is_file():
        raise FileNotFoundError(f"GOW executable not found: {executable}")

    if not specification.is_file():
        raise FileNotFoundError(
            f"Official toy specification not found: {specification}"
        )

    outdir.mkdir(parents=True, exist_ok=True)

    command = [
        str(executable),
        "run",
        str(specification),
        "--outdir",
        str(outdir),
        "--run-id",
        run_id,
    ]

    print(f"Output directory: {outdir}")
    print(f"Run ID: {run_id}")
    print("Starting the official real GOW toy campaign...")

    gow_process = subprocess.Popen(
        command,
        cwd=gow_root,
        text=True,
    )

    print(f"GOW root PID: {gow_process.pid}")

    monitor_process: subprocess.Popen[str] | None = None

    if not arguments.no_launch_monitor:
        monitor_process = subprocess.Popen(
            [
                sys.executable,
                "-m",
                "gow_monitor",
                "--results-root",
                str(outdir),
                "--gow-pid",
                str(gow_process.pid),
            ],
            cwd=Path.cwd(),
            text=True,
        )
        print(f"GOW Monitor PID: {monitor_process.pid}")
        time.sleep(1.0)

    try:
        return_code = gow_process.wait()
    except KeyboardInterrupt:
        print("Stopping the real GOW smoke campaign...")
        gow_process.terminate()

        try:
            return_code = gow_process.wait(timeout=5.0)
        except subprocess.TimeoutExpired:
            gow_process.kill()
            return_code = gow_process.wait(timeout=5.0)

    run_root = outdir / "runs" / run_id
    result_count = (
        len(tuple(run_root.rglob("result.json")))
        if run_root.is_dir()
        else 0
    )

    print(f"GOW return code: {return_code}")
    print(f"Run root: {run_root}")
    print(f"result.json files observed: {result_count}")

    if monitor_process is not None:
        print(
            "GOW Monitor remains open for visual inspection. "
            "After GOW exits, its process telemetry should become unavailable "
            "while host telemetry remains active."
        )

    return return_code


if __name__ == "__main__":
    raise SystemExit(main())
